services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false # You will set this manually in the Render dashboard